language: java

script: "mvn deploy --settings travis/settings.xml"

jdk:
  - oraclejdk7

env:
  global:
  - secure: "VBNeW0ob0Bc8FCQllHaQsRnbKCHZcmdwi3QA13vdn+4g84/601kRv/XvQ4d4gvzKfVNULBzOh9JBM7uZEerrroxRfzVXKjQ0yLjnwkb8zssPNkDNGAg/cOfrUz55bdv5CTwkmVT0iSCu1xoIVqZNKISgwjT4yK0KMb/cOqp8fHo="
  - secure: "f1qX5i2iXSxYTwrLUlOshzCTHC4YM+FQ2hjM0LOTO6UGGgUB1jvJ58vO4Mob4gfHUlmZt1ULyXmmGbh0H4dxCGQxgiHFiWPMRQ9xeDWapEIq11HPCX7G/E+bt5igThppaVSQ2kNLFn0rCBtBhhYouxQJO+sPm/ANsacCNrU8oHY="

